version: "3.8"

services:
  mysql:
    image: mysql
    container_name: MySQL
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - MySQL-Data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  MySQL-Data:
